server:
  port: 8080

spring:
  application:
    name: fitstream

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fitstream_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: fitstream-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss}){cyan} | %clr(%-5level){highlight} | %clr(${spring.application.name}){magenta} | %clr(%logger{20}){yellow} | %msg%n"
  level:
    org.springframework: INFO
    org.hibernate: ERROR
