ALTER TABLE workouts DROP COLUMN title;
ALTER TABLE workouts DROP COLUMN description;

ALTER TABLE workouts ADD COLUMN exercise VARCHAR(255) NOT NULL;
ALTER TABLE workouts ADD COLUMN sets INT NOT NULL DEFAULT 1;
ALTER TABLE workouts ADD COLUMN reps INT NOT NULL DEFAULT 1;
ALTER TABLE workouts ADD COLUMN weight DOUBLE PRECISION NOT NULL DEFAULT 0.0;
