ALTER TABLE meals DROP COLUMN IF EXISTS description;

ALTER TABLE meals ADD COLUMN IF NOT EXISTS calories INT NOT NULL DEFAULT 0;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS protein INT NOT NULL DEFAULT 0;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS carbs INT NOT NULL DEFAULT 0;
ALTER TABLE meals ADD COLUMN IF NOT EXISTS fat INT NOT NULL DEFAULT 0;
